### ISSUE TITLE
Auth provider for Azure?

### ISSUE THREAD

**Issue by krisalyssa** [coryodaniel/k8s#162]
Before I dive down the rabbit hole of implementing my own auth provider, has anyone gotten the `k8s` library working with Azure AKS?

The problem I'm encountering trying to use `k8s` out of the box is that the user config in `~/.kube/config` looks like it should be handled by the standard `AuthProvider` module, but it contains a different set of keys.

```
- name: clusterUser_dve2-rg-nonprod-k8s_dve2-aks-nonprod
  user:
    auth-provider:
      config:
        access-token: ***
        apiserver-id: ***
        client-id: ***
        config-mode: "1"
        environment: AzurePublicCloud
        expires-in: "5264"
        expires-on: "1652716095"
        refresh-token: ***
        tenant-id: ***
      name: azure
```

None of the keys in the destructuring at https://github.com/coryodaniel/k8s/blob/1.1.4/lib/k8s/conn/auth/auth_provider.ex#L22-L27 exist, so the code bombs out with "no match of right hand side".
